# see: https://github.com/marketplace/actions/deploy-mkdocs
name: Publish docs via GitHub Pages

on: pull_request
permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0.24.0
        with:
          # mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'requirements-mkdocs.txt' # option
          configfile: 'mkdocs.yml' # option
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #   # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     #CUSTOM_DOMAIN: optionaldomain.com
      #     CONFIG_FILE: mkdocs.yml
      #     EXTRA_PACKAGES: build-base
      #     # GITHUB_DOMAIN: github.myenterprise.com
      #     REQUIREMENTS: requirements-mkdocs.txt
