name: New Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  call-build_exe:
    uses: ./.github/workflows/build_exe.yml
    with:
      is_release: true
    secrets:
      APPLE_DEV_EMAIL: ${{ secrets.APPLE_DEV_EMAIL }}
      APP_SPEC_PASS: ${{ secrets.APP_SPEC_PASS }}
      DEV_APP_CERT: ${{ secrets.DEV_APP_CERT }}
      DEV_APP_CERT_PASS: ${{ secrets.DEV_APP_CERT_PASS }}
      DEV_INST_CERT: ${{ secrets.DEV_INST_CERT }}
      DEV_INST_CERT_PASS: ${{ secrets.DEV_INST_CERT_PASS }}
      APPLE_KEY_PASS: ${{ secrets.APPLE_KEY_PASS }}
      APPLE_APP_CERT_ID: ${{ secrets.APPLE_APP_CERT_ID }}
      APPLE_INST_CERT_ID: ${{ secrets.APPLE_INST_CERT_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
  release:
    needs: call-build_exe
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: artifacts/windows

      - name: Download macOS Universal artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-universal
          path: artifacts/macos-universal

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
